services:
  pageserver:
    container_name: pageserver
    hostname: pageserver

    build:
      context: .
      dockerfile: pageserver.Dockerfile
    image: 32kb.org:5000/pageserver
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./token_data:/home/worker/token_data
      - ./battles:/home/worker/battles

  gameserver:
    container_name: gameserver
    hostname: gameserver

    build:
      context: .
      dockerfile: gameserver.Dockerfile
    image: 32kb.org:5000/gameserver
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./token_data:/home/worker/token_data
      - ./battles:/home/worker/battles

  minter:
    container_name: minter
    hostname: minter

    build:
      context: .
      dockerfile: minter.Dockerfile
    image: 32kb.org:5000/minter
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./accounts:/home/worker/accounts
      - ./token_data:/home/worker/hashlips_art_engine/build
      - ./token_data/dnalist.json:/home/worker/hashlips_art_engine/dnalist.json

  proxy:
    container_name: g4n9-proxy
    hostname: g4n9-proxy
    volumes:
      - ./ReverseProxy/vhosts:/etc/nginx/conf.d
      - ./static:/var/www/g4n9
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: 32kb.org:5000/proxy

  tracker:
    container_name: tracker
    hostname: tracker
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./battles:/home/worker/battles
    build:
      context: .
      dockerfile: tracker.Dockerfile
    image: 32kb.org:5000/tracker

networks:
  default:
    name: dockernet
    external: true